basePath: /api
definitions:
  models.ServerConfigFileInfo:
    properties:
      exists:
        description: 文件是否存在
        type: boolean
      file_name:
        description: 文件名
        type: string
      file_path:
        description: 文件完整路径
        type: string
      file_size:
        description: 文件大小（字节）
        type: integer
      last_modified:
        description: 最后修改时间
        type: string
    type: object
  models.ServerConfigRequest:
    properties:
      game_ini:
        description: Game.ini 文件内容
        type: string
      game_user_settings:
        description: GameUserSettings.ini 文件内容
        type: string
    type: object
  models.ServerConfigResponse:
    properties:
      game_ini:
        description: Game.ini 文件内容
        type: string
      game_ini_path:
        description: Game.ini 文件路径
        type: string
      game_user_settings:
        description: GameUserSettings.ini 文件内容
        type: string
      game_user_settings_path:
        description: GameUserSettings.ini 文件路径
        type: string
      server_id:
        type: integer
      server_name:
        type: string
      updated_at:
        type: string
    type: object
  models.ServerRequest:
    properties:
      admin_password:
        type: string
      description:
        type: string
      map:
        type: string
      max_players:
        maximum: 200
        minimum: 1
        type: integer
      name:
        type: string
      port:
        maximum: 65535
        minimum: 1
        type: integer
      query_port:
        maximum: 65535
        minimum: 1
        type: integer
      rcon_port:
        maximum: 65535
        minimum: 1
        type: integer
    required:
    - admin_password
    - max_players
    - name
    - port
    - query_port
    - rcon_port
    type: object
  models.ServerResponse:
    properties:
      admin_password:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      map:
        type: string
      max_players:
        type: integer
      name:
        type: string
      port:
        type: integer
      query_port:
        type: integer
      rcon_port:
        type: integer
      status:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.ServerUpdateRequest:
    properties:
      admin_password:
        type: string
      description:
        type: string
      map:
        type: string
      max_players:
        maximum: 200
        minimum: 1
        type: integer
      name:
        type: string
      port:
        maximum: 65535
        minimum: 1
        type: integer
      query_port:
        maximum: 65535
        minimum: 1
        type: integer
      rcon_port:
        maximum: 65535
        minimum: 1
        type: integer
    type: object
  models.UserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.UserResponse:
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API支持
    url: http://www.swagger.io/support
  description: 基于Gin+Gorm的ARK服务器管理系统API文档
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: ARK服务器管理器 API
  version: "1.0"
paths:
  /auth/check-init:
    get:
      consumes:
      - application/json
      description: 检查系统是否已经初始化过用户
      produces:
      - application/json
      responses:
        "200":
          description: 初始化状态
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: 检查系统初始化状态
      tags:
      - 认证
  /auth/init:
    post:
      consumes:
      - application/json
      description: 创建第一个管理员用户，只能在系统未初始化时调用
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 初始化成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 初始化系统用户
      tags:
      - 认证
  /auth/login:
    post:
      consumes:
      - application/json
      description: 使用用户名和密码登录系统
      parameters:
      - description: 登录凭据
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 认证失败
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - 认证
  /profile:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户的基本信息
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            additionalProperties:
              $ref: '#/definitions/models.UserResponse'
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取当前用户信息
      tags:
      - 用户
  /servers:
    get:
      consumes:
      - application/json
      description: 获取当前用户的所有服务器列表
      produces:
      - application/json
      responses:
        "200":
          description: 服务器列表
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/models.ServerResponse'
              type: array
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取服务器列表
      tags:
      - 服务器管理
    post:
      consumes:
      - application/json
      description: 创建一个新的ARK服务器配置
      parameters:
      - description: 服务器配置
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 创建成功
          schema:
            additionalProperties:
              $ref: '#/definitions/models.ServerResponse'
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 创建新服务器
      tags:
      - 服务器管理
  /servers/{id}:
    delete:
      consumes:
      - application/json
      description: 删除指定的服务器配置（仅允许删除已停止的服务器）
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 删除服务器
      tags:
      - 服务器管理
    get:
      consumes:
      - application/json
      description: 根据ID获取指定服务器的详细信息
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 服务器信息
          schema:
            additionalProperties:
              $ref: '#/definitions/models.ServerResponse'
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取服务器详情
      tags:
      - 服务器管理
    put:
      consumes:
      - application/json
      description: 更新指定服务器的配置信息
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新的服务器配置
        in: body
        name: server
        required: true
        schema:
          $ref: '#/definitions/models.ServerUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            additionalProperties:
              $ref: '#/definitions/models.ServerResponse'
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 更新服务器配置
      tags:
      - 服务器管理
  /servers/{id}/config:
    get:
      consumes:
      - application/json
      description: 获取指定服务器的INI配置文件内容（GameUserSettings.ini和Game.ini）
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 配置文件内容
          schema:
            additionalProperties:
              $ref: '#/definitions/models.ServerConfigResponse'
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取服务器配置文件
      tags:
      - 服务器管理
    put:
      consumes:
      - application/json
      description: 更新指定服务器的INI配置文件内容（GameUserSettings.ini和Game.ini）
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      - description: 配置文件内容
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/models.ServerConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            additionalProperties:
              $ref: '#/definitions/models.ServerConfigResponse'
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 更新服务器配置文件
      tags:
      - 服务器管理
  /servers/{id}/config/files:
    get:
      consumes:
      - application/json
      description: 列出指定服务器配置目录下的所有INI文件
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 配置文件列表
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/models.ServerConfigFileInfo'
              type: array
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 列出服务器配置文件
      tags:
      - 服务器管理
  /servers/{id}/folder:
    get:
      consumes:
      - application/json
      description: 获取指定服务器的文件夹路径和大小（仅供内部管理使用）
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 文件夹信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取服务器文件夹信息
      tags:
      - 服务器管理
  /servers/{id}/rcon:
    get:
      consumes:
      - application/json
      description: 获取指定服务器的RCON连接信息（包括密码）
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: RCON信息
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 获取服务器RCON信息
      tags:
      - 服务器管理
  /servers/{id}/start:
    post:
      consumes:
      - application/json
      description: 启动指定的ARK服务器
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 启动成功
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 启动服务器
      tags:
      - 服务器管理
  /servers/{id}/stop:
    post:
      consumes:
      - application/json
      description: 停止指定的ARK服务器
      parameters:
      - description: 服务器ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 停止成功
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 请求错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: 服务器不存在
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 停止服务器
      tags:
      - 服务器管理
securityDefinitions:
  Bearer:
    description: JWT token in the format "Bearer {token}"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
